import FolderImage from "../img/FolderImg"

const dataModalApprove = [
    {   
        InformationTrip : [
            ["Date Trip", FolderImage.Hotel, "02 Februari 2024"],
            ["Duration",FolderImage.Time, "6 Day 4 Night",],
            ["Accomodation", FolderImage.Calendar, "Hotel 3 Night",],
            ["Transportation", FolderImage.Plane, "Bus Damri"],
        ],
        No : "1",
        Users : "dika",
        Gender : "male",
        Phone : "081234543210",
        Amount : 5,
        Total : 35940000,
        Trip : "4D/3N Unforgettable Adventures Await in Lampung!",
        Country: "Lampung",
        DateBooking : "25 mei 2020",
        StatusPayment : "Approve",
        Action : FolderImage.Magnifying,
    },
    {   
        InformationTrip : [
            ["Date Trip", FolderImage.Hotel, "17 Juni 2024"],
            ["Duration",FolderImage.Time, "6 Day 4 Night",],
            ["Accomodation", FolderImage.Calendar, "Hotel 4 Night",],
            ["Transportation", FolderImage.Plane, "Garuda Indonesia"],
        ],
        No : "2",
        Users : "mas Handika",
        Gender : "male",
        Phone : "081234543210",
        Amount : 7,
        Total : 73416000,
        Trip :  "5D/4N Nusa Tenggara Timur Beckons: Your Ideal Destination for an Incredible Holiday!",
        Country: "Nusa Tenggara Timur",
        DateBooking : "25 mei 2020",
        StatusPayment : "Approve",
        Action : FolderImage.Magnifying,
    },
    {   
        InformationTrip : [
            ["Date Trip", FolderImage.Hotel, "26 Agustus 2024"],
            ["Duration",FolderImage.Time, "6 Day 4 Night",],
            ["Accomodation", FolderImage.Calendar, "Hotel 4 Night",],
            ["Transportation", FolderImage.Plane, "Japan Airlines"],
        ],
        No : "3",
        Users : "Abang Al",
        Gender : "male",
        Phone : "081234543210",
        Amount : 12,
        Total : 123456000,
        Trip :  "6D/4N Fun Tassie Vacation in Japan",
        Country: "Japan",
        DateBooking : "25 mei 2020",
        StatusPayment : "Cancel",
        Action : FolderImage.Magnifying,
    },
    {   
        InformationTrip : [
            ["Date Trip", FolderImage.Hotel, "15 Oktober 2024"],
            ["Duration",FolderImage.Time, "6 Day 4 Night",],
            ["Accomodation", FolderImage.Calendar, "Hotel 6 Night",],
            ["Transportation", FolderImage.Plane, "Korean Air"],
        ],
        No : "4",
        Users : "Bro falaq",
        Gender : "male",
        Phone : "081234543210",
        Amount : 25,
        Total : 474975000,
        Trip :  "8D/6N Embark on an Extraordinary Holiday in Korea Selatan's Wonderland!",
        Country: "Korea Selatan",
        DateBooking : "25 mei 2020",
        StatusPayment : "Cancel",
        Action : FolderImage.Magnifying,
    },
    {   
        InformationTrip : [
            ["Date Trip", FolderImage.Hotel, "15 Desember 2024"], //1
            ["Duration",FolderImage.Time, "6 Day 4 Night",], //2
            ["Accomodation", FolderImage.Calendar, "Hotel 4 Night"], //3
            ["Transportation", FolderImage.Plane, "Virgin Australia"], //4      
        ],
        No : "5",
        Users : "handika al falaq",
        Gender : "male",
        Phone : "081234543210",
        Amount : 17,
        Total : 210766000,
        Trip :  "6D/4N Great Holiday in Australia",
        Country: "Australia",
        DateBooking : "25 mei 2020",
        StatusPayment : "Pending",
        Action : FolderImage.Magnifying,
    },
    {   
        InformationTrip : [
            ["Date Trip", FolderImage.Hotel, "17 Juni 2024"],
            ["Duration",FolderImage.Time, "6 Day 4 Night",],
            ["Accomodation", FolderImage.Calendar, "Hotel 4 Night",],
            ["Transportation", FolderImage.Plane, "Garuda Indonesia"],
        ],
        No : "6",
        Users : "Al Falaq",
        Gender : "male",
        Phone : "081234543210",
        Amount : 9,
        Total : 100692000,
        Trip :  "5D/4N Escape to Paradise: Explore Papua's Stunning Landscapes!",
        Country: "Papua",
        DateBooking : "25 mei 2020",
        StatusPayment : "Cancel",
        Action : FolderImage.Magnifying,
    },
]

export default dataModalApprove